
.TH zuluPolkit 1

.br
.SH NAME
zuluPolkit - It is a handler the polkit privileges

.SH SYNOPSIS
zuluPolkit - It is a handler the polkit privileges
.br
.SH DESCRIPTION
zuluPolkit is a tool that handle polkit for zulucrypt-gui and zulumount-gui.
.br

.SH AUTHOR
The \fBzuluPolkit\fP was written by Ink Francis Aka Mhogo Mchungu <mhogomchungu@gmail.com>.
This manual page was written by Marcio de Souza Oliveira <m.desouza20@gmail.com> for the Debian project (but may be used by others).
